### ISSUE TITLE
Command palette freezing app with tasks-x enabled

### ISSUE THREAD

**Issue by takeo** [sytone/obsidian-tasks-x#1]
Issue tracker is **ONLY** used for reporting bugs. New feature ideas should be discussed in the [ideas section](https://github.com/sytone/obsidian-tasks-x/discussions/categories/ideas). Please use the [Q&A section](https://github.com/sytone/obsidian-tasks-x/discussions/categories/q-a) for supporting issues. Please use the search function.

If you encountered the issue after you installed, updated, or reloaded the tasks plugin, please try restarting obsidian before reporting the bug.

If you want to report a bug, please follow the guide lines below to help me resolve it.

## Expected Behavior
cmd-p should open the command palette

## Current Behavior
command-p seems to freeze the entire app for about a minute and spikes the cpu to 100%. When it finally comes back the console logs this:

`[20220530 08:43:33][SILLY] [Command:debug-export-tasks] Checking if command is available.,[object Object],[object Object] plugin:obsidian-tasks-x-plugin:176`

## Steps to Reproduce
In my current setup it's just hitting cmd-p or clicking the command palette.

## Context (Environment)
* Obsidian version: 0.14.5
* Tasks version: 2.0.6
* [-] I have tried it with all other plugins disabled and the error still occurs

In my vault with lots of plugins this was happening every time. In a new vault with only BRAT, this plugin, and minimal theme it seemed ok. Not too sure what could be conflicting with it, but the regular tasks plugin works fine in my vault. Let me know if there's anything I can do to help narrow it down. I'm super excited to try your version out.

**Comment by sytone** [comment]
Yea. Had some issues with the logging. Manage to log a few million lines. :)

The current version resolved that issue. Can you update and let me know? I'm adding a UI option to set the logging threshold in the next day or so. Working on issues with mobile support at the moment.

**Comment by sytone** [comment]
Ok, 2.0.11 should have this all fixed. Tested on android and desktop and not seeing issues with the command pallet opening.

**Comment by takeo** [comment]
Looks like 2.0.11 fixes the command palette problem. Thanks!
