### ISSUE TITLE
Created Date appearing Twice

### ISSUE THREAD

**Issue by stefanopagliari** [sytone/obsidian-tasks-x#13]
Issue tracker is **ONLY** used for reporting bugs. New feature ideas should be discussed in the [ideas section](https://github.com/sytone/obsidian-tasks-x/discussions/categories/ideas). Please use the [Q&A section](https://github.com/sytone/obsidian-tasks-x/discussions/categories/q-a) for supporting issues. Please use the search function.

If you encountered the issue after you installed, updated, or reloaded the tasks plugin, please try restarting obsidian before reporting the bug.

If you want to report a bug, please follow the guide lines below to help me resolve it.

## Expected Behavior
The ➕DATE should appear only once when this date is added

## Current Behavior
In the case a task does not have a created date (pre-existing ones), then the current date is shows. 

![image](https://user-images.githubusercontent.com/30759878/177137488-fe7c2a97-1645-463c-8d42-f64f56ac4e14.png)

When a task already had a created date (added manually before installing the plugin) then two dates are shown (as in the screenshot)
![image](https://user-images.githubusercontent.com/30759878/177137851-b0d59278-d48e-4d32-9ca7-c33f2d748d4c.png)

 
## Context (Environment)

* Obsidian version: v. 0.15.3
* Tasks version: 2.6.1
* [ ] I have tried it with all other plugins disabled and the error still occurs

**Comment by stefanopagliari** [comment]
Another anomaly with the "created task" is that when I open the task using the "Create or Edit Task" panel, the panel does not recognise the created date as already part of the text. As a result, a new created date is added. 
![image](https://user-images.githubusercontent.com/30759878/177401253-27f6aaf6-5a17-47d4-b618-fe8855c02813.png)

**Comment by stefanopagliari** [comment]
I found out another but that results from the plugin not recognising the created date as already in the text. Every time the status of the task changes, a new created date is added. In the example below there are three different created dates that were added 1) once the task was created, 2) one the status was changed on [-] and 3) once the task was completed 
![image](https://user-images.githubusercontent.com/30759878/177722324-57d671a1-19a2-42f7-972a-5c822500e3a0.png)

**Comment by sytone** [comment]
Thanks for the feedback. Created is using a new parsing approach. When back and able to look at issues in a few weeks will resolve it out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sytone** [comment]
@stefanopagliari thanks for the feedback, I have found the issue and creating a patch to resolve it. I was able to reproduce the issue you saw.
