### ISSUE TITLE
Editing/Adding Custom Task Types Not Saving

### ISSUE THREAD

**Issue by takeo** [sytone/obsidian-tasks-x#4]
## Expected Behavior
Tasks status types should save when changed/added

## Current Behavior
Changing the "next status symbol" field is not saving.

## Steps to Reproduce
* Change the "next status symbol" field in one of the task types.
* Close the settings
* Reopen settings
* Field has reverted to `x`

![CleanShot 2022-06-01 at 21 41 37](https://user-images.githubusercontent.com/23/171554515-4cf79723-21e4-4e6f-8730-e00a244ffbf7.gif)

## Context (Environment)
* Obsidian version: 0.14.15
* Tasks version: 2.0.11
* [-] I have tried it with all other plugins disabled and the error still occurs

## Possible Solution
Fix `updateStatusSetting()`

![CleanShot 2022-06-01 at 22 10 23@2x](https://user-images.githubusercontent.com/23/171557288-eebaeaea-946c-4d82-a223-93daa9e2885a.png)

**Comment by sytone** [comment]
Updated the UI to use a modal for editing which makes it cleaner and resolves this bug. 

![image](https://user-images.githubusercontent.com/1399443/172076480-af5850eb-a59b-49c8-9151-9fb5ca757c42.png)
