### ISSUE TITLE
BRAT reports main.js missing from v2.0.13 release

### ISSUE THREAD

**Issue by claremacrae** [sytone/obsidian-tasks-x#6]
In case you aren't aware...

## Expected Behavior

Plugin can be installed from BRAT

## Current Behavior

Error message about 'main.js missing from release'

![image](https://user-images.githubusercontent.com/4840096/171912438-2c087746-b294-4230-a076-f7330770cb80.png)

## Steps to Reproduce

Ask BRAT to load `sytone/obsidian-tasks-x`

## Context (Environment)
* Obsidian version:
* Tasks version: not relevant - the current obsidian-tasks-x release is `v2.0.13`
* [ ] I have tried it with all other plugins disabled and the error still occurs

**Comment by sytone** [comment]
Thanks. I managed to add a v in front of the version. 🤦‍♂️

Fixing it shortly.

**Comment by sytone** [comment]
Resolved.
