### ISSUE TITLE
'not done' filter returning all statuses

### ISSUE THREAD

**Issue by blujaxfan** [sytone/obsidian-tasks-x#9]
Using the 'not done' filter does not filter out 'done' tasks

For these tasks:
- [ ] This is a task 1
- [x] This is a task 2 (done)

And this code block:

<img width="206" alt="CleanShot 2022-06-24 at 17 18 50@2x" src="https://user-images.githubusercontent.com/60331895/175679653-211ac891-535c-4485-8cc2-ebf667bfc6aa.png">

Yields attached result
<img width="449" alt="CleanShot 2022-06-24 at 17 16 01@2x" src="https://user-images.githubusercontent.com/60331895/175675542-b05bebf2-b9bd-4131-a0ee-77f54575cb72.png">

**Comment by craldaz** [comment]
same

**Comment by sytone** [comment]
I have been able to reproduce this issue and have a fix for it to go in shortly.
